version: '3'

services:
  mongodb:
      image: mongo:7.0.16
      ports:
        - "27017:27017"
      env_file:
        - ../api/.env
      volumes:
        - 'sphere-mongodb:/data/db'
        - '../api/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh'
      networks:
        - sphere-network
volumes:
  sphere-mongodb:
    driver: local
networks:
  sphere-network:
    driver: bridge