version: '3'

services:
  mongodb:
      image: mongo:7.0.16
      ports:
        - "27017:27017"
      env_file:
        - ../api/.env.production
      volumes:
        - 'sphere-mongodb:/data/db'
        - '../api/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh'
      networks:
        - sphere-network
  server:
    restart: always
    container_name: sphere-server
    build:
        context: ../api
        dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ../api/.env.production
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - sphere-network
  client:
    restart: always
    container_name: sphere-client
    build:
        context: ../frontend
        dockerfile: ./docker/Dockerfile
    ports:
      - 5173:5173
    env_file:
      - ../frontend/.env.production
    networks:
      - sphere-network
  nginx:
    restart: always
    container_name: sphere-nginx
    build:
        context: ../nginx/local
        dockerfile: ./Dockerfile
    ports:
      - 80:80
    depends_on:
      - server
      - client
    networks:
      - sphere-network
volumes:
  sphere-mongodb:
    driver: local
networks:
  sphere-network:
    driver: bridge