name: Unit Tests Run
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DATABASE_TECHNOLOGY: ${{vars.CI_DATABASE_TECHNOLOGY}}
          envkey_MONGO_PROTOCOL: ${{vars.CI_MONGO_PROTOCOL}}
          envkey_MONGO_HOST: ${{vars.CI_MONGO_HOST}}
          envkey_MONGO_PORT: ${{vars.CI_MONGO_PORT}}
          envkey_MONGO_INITDB_DATABASE: ${{vars.CI_MONGO_INITDB_DATABASE}}
          envkey_MONGO_INITDB_ROOT_USERNAME: ${{vars.CI_MONGO_INITDB_ROOT_USERNAME}}
          envkey_MONGO_INITDB_ROOT_PASSWORD: ${{vars.CI_MONGO_INITDB_ROOT_PASSWORD}}
          envkey_DATABASE_NAME: ${{vars.CI_MONGO_INITDB_DATABASE}}
          envkey_DATABASE_USERNAME: ${{vars.CI_MONGO_INITDB_ROOT_USERNAME}}
          envkey_DATABASE_PASSWORD: ${{vars.CI_MONGO_INITDB_ROOT_PASSWORD}}
          envkey_SERVER_PORT: ${{vars.CI_SERVER_PORT}}
          envkey_APP_HOST: ${{vars.CI_APP_HOST}}
          envkey_AVATARS_FOLDER: ${{vars.CI_AVATARS_FOLDER}}
          envkey_BASE_URL_PATH: ${{vars.CI_BASE_URL_PATH}}
          directory: ./api
          file_name: .env
          fail_on_empty: false
          sort_keys: false

      - name: Start MongoDBs
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '7.0.16'
          mongodb-username: ${{ vars.CI_MONGO_INITDB_ROOT_USERNAME }}
          mongodb-password: ${{ vars.CI_MONGO_INITDB_ROOT_PASSWORD }}
          mongodb-db: ${{ vars.CI_MONGO_INITDB_DATABASE }}
          mongodb-port: ${{ vars.CI_MONGO_PORT }}

      - name: Install dependencies
        run: npm run install

      - name: Run tests
        run: npm run test
